name: Build/Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    # Buradaki izinleri ekliyoruz:
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js
        run: npm run next:build

      - name: Build and Release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true